Update README.md
hakimel/reveal.js pull request #2913
Opened 2021-03-06 06:39 UTC by bkmgit

Update copyright year

2021-03-24 17:13 UTC, panda0070923 approved these changes

2021-04-06 08:04 UTC, deezwayne approved these changes

2021-04-28 10:54 UTC, fuckoff1989 requested changes
What

2021-05-05 08:04 UTC, hakimel commented
Thanks, I'll make this change in the dev branch.

2021-05-05 08:04 UTC, closed without merging